import { createClient } from '@supabase/supabase-js';
import dotenv from 'dotenv';
dotenv.config();

const supabase = createClient(
    process.env.SUPABASE_URL, 
    process.env.SUPABASE_SERVICE_KEY || process.env.SUPABASE_ANON_KEY
);

async function checkMableJanuary() {
    console.log('🔍 CHECKING GENERATE MISSING PUNCHES & MABLE\'S JANUARY LOGS\n');
    console.log('='.repeat(100));
    
    // 1. Check if missing days generator has run recently
    console.log('\n📋 PART 1: CHECKING MISSING DAYS GENERATOR STATUS\n');
    
    // Find user
    const { data: user, error: userError } = await supabase
        .from('opoint_users')
        .select('*')
        .eq('email', 'mablepernarh@gmail.com')
        .single();
    
    if (userError || !user) {
        console.log('❌ User not found:', userError?.message);
        return;
    }
    
    console.log(`👤 User: ${user.name}`);
    console.log(`   Email: ${user.email}`);
    console.log(`   ID: ${user.id}`);
    console.log(`   Tenant ID: ${user.tenant_id}\n`);
    
    // Check for auto-generated entries (missing days generator output)
    const { data: autoGenerated, error: autoError } = await supabase
        .from('opoint_clock_logs')
        .select('*')
        .eq('employee_id', user.id)
        .eq('location', 'Auto-generated (no punch)')
        .order('date', { ascending: false })
        .limit(10);
    
    if (autoGenerated && autoGenerated.length > 0) {
        console.log(`✅ MISSING DAYS GENERATOR IS WORKING!`);
        console.log(`   Found ${autoGenerated.length} auto-generated entries (last 10):\n`);
        autoGenerated.forEach((entry, i) => {
            console.log(`   ${i + 1}. ${entry.date} - Location: "${entry.location}"`);
            console.log(`      Punches: ${entry.punches?.length || 0} items`);
        });
    } else {
        console.log(`⚠️  No auto-generated entries found`);
        console.log(`   This could mean:`);
        console.log(`   - Generator hasn't run yet (runs at midnight))`);
        console.log(`   - User has punched in every day`);
        console.log(`   - Generator encountered an error\n`);
    }
    
    // 2. Get all January 2026 clock logs
    console.log('\n' + '='.repeat(100));
    console.log('\n📋 PART 2: JANUARY 2026 CLOCK LOGS FOR MABLE\n');
    
    const { data: januaryLogs, error: logsError } = await supabase
        .from('opoint_clock_logs')
        .select('*')
        .eq('employee_id', user.id)
        .gte('date', '2026-01-01')
        .lte('date', '2026-01-31')
        .order('date', { ascending: true });
    
    if (logsError) {
        console.log('❌ Error fetching logs:', logsError.message);
        return;
    }
    
    if (!januaryLogs || januaryLogs.length === 0) {
        console.log('❌ No January 2026 logs found for this user');
        return;
    }
    
    console.log(`📊 Found ${januaryLogs.length} clock log entries for January 2026\n`);
    
    let totalHoursWorked = 0;
    
    januaryLogs.forEach((log, index) => {
        console.log(`\n📅 DAY ${index + 1}: ${log.date}`);
        console.log('─'.repeat(100));
        
        // Basic info
        console.log(`   Clock In:     ${log.clock_in || 'NULL'}`);
        console.log(`   Clock Out:    ${log.clock_out || 'NULL'}`);
        console.log(`   Clock In 2:   ${log.clock_in_2 || 'NULL'}`);
        console.log(`   Clock Out 2:  ${log.clock_out_2 || 'NULL'}`);
        console.log(`   Location:     ${log.location || 'NULL'}`);
        console.log(`   Still Working: ${log.still_working}`);
        
        // Adjustment info
        if (log.adjustment_status) {
            console.log(`   Adjustment Status: ${log.adjustment_status}`);
            console.log(`   Adjustment Applied: ${log.adjustment_applied || 'NULL'}`);
        }
        
        // Punches array
        console.log(`\n   📦 PUNCHES ARRAY:`);
        if (log.punches && Array.isArray(log.punches) && log.punches.length > 0) {
            console.log(`      Total punches: ${log.punches.length}`);
            
            let dayHours = 0;
            log.punches.forEach((punch, i) => {
                if (typeof punch === 'object' && punch.time) {
                    const punchTime = new Date(punch.time);
                    const timeStr = punchTime.toLocaleTimeString('en-GB');
                    console.log(`      ${i + 1}. ${punch.type.toUpperCase().padEnd(3)} - ${timeStr} ${punch.location ? '- ' + punch.location : ''}`);
                } else {
                    console.log(`      ${i + 1}. ${JSON.stringify(punch).substring(0, 80)}`);
                }
            });
            
            // Calculate hours from punches (pair in/out)
            console.log(`\n   ⏱️  HOURS CALCULATION:`);
            for (let i = 0; i < log.punches.length; i += 2) {
                if (log.punches[i] && log.punches[i + 1]) {
                    const inPunch = log.punches[i];
                    const outPunch = log.punches[i + 1];
                    
                    let inTime, outTime;
                    if (typeof inPunch === 'object' && inPunch.time) {
                        inTime = new Date(inPunch.time);
                        outTime = new Date(outPunch.time);
                    } else {
                        inTime = new Date(inPunch);
                        outTime = new Date(outPunch);
                    }
                    
                    const diffMs = outTime - inTime;
                    const hours = diffMs / (1000 * 60 * 60);
                    
                    if (hours > 0) {
                        dayHours += hours;
                        const h = Math.floor(hours);
                        const m = Math.floor((hours - h) * 60);
                        console.log(`      Pair ${Math.floor(i/2) + 1}: ${inTime.toLocaleTimeString('en-GB')} → ${outTime.toLocaleTimeString('en-GB')} = ${h}h ${m}m`);
                    }
                }
            }
            
            totalHoursWorked += dayHours;
            const h = Math.floor(dayHours);
            const m = Math.floor((dayHours - h) * 60);
            console.log(`      ✅ Day Total: ${h}h ${m}m (${dayHours.toFixed(2)} hours)`);
            
        } else if (log.punches && log.punches.length === 0) {
            console.log(`      ⚠️  Empty array (auto-generated or no punches)`);
        } else {
            console.log(`      ❌ NULL or not an array`);
        }
    });
    
    // Summary
    console.log('\n' + '='.repeat(100));
    console.log('\n📊 JANUARY 2026 SUMMARY FOR MABLE\n');
    console.log(`   Total Days Logged: ${januaryLogs.length}`);
    console.log(`   Total Hours Worked: ${totalHoursWorked.toFixed(2)} hours`);
    
    const h = Math.floor(totalHoursWorked);
    const m = Math.floor((totalHoursWorked - h) * 60);
    console.log(`   Time Format: ${h}h ${m}m\n`);
    
    // Check for missing days generator entries
    const autoGenDays = januaryLogs.filter(log => log.location === 'Auto-generated (no punch)');
    if (autoGenDays.length > 0) {
        console.log(`   🔧 Auto-Generated Days: ${autoGenDays.length}`);
        autoGenDays.forEach(day => {
            console.log(`      - ${day.date}`);
        });
    }
    
    console.log('\n' + '='.repeat(100));
}

checkMableJanuary().catch(console.error);
